# Generated by Django 5.1.1 on 2024-10-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
    ]
