# Generated by Django 5.1.1 on 2024-10-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
    ]
