# Generated by Django 5.1.1 on 2024-10-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_slug'),
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
    ]
